<script setup lang="ts">
import { nextTick, onMounted, reactive, ref } from 'vue'
import type { Customer } from '../../types/customer'
import type { TeamMember } from '../../types/dashboard'
import type { CreateOpportunityInput, OpportunityStage } from '../../types/opportunity'
import { defaultStageProbabilities, opportunityStageLabels } from '../../utils/opportunity'
const props = defineProps<{ customers: Customer[]; members: TeamMember[] }>(); const emit = defineEmits<{ close: []; create: [input: CreateOpportunityInput] }>()
const dialog=ref<HTMLElement|null>(null);const titleInput=ref<HTMLInputElement|null>(null);const error=ref('');const form=reactive<CreateOpportunityInput>({title:'',customerId:'',value:0,stage:'lead',probability:20,expectedCloseDate:'',ownerId:''})
const stages: OpportunityStage[] = ['lead', 'contacted', 'proposal', 'negotiation', 'won', 'lost']
function setStage(event:Event){const stage=(event.target as HTMLSelectElement).value as OpportunityStage;form.stage=stage;form.probability=defaultStageProbabilities[stage]}
function submit(){error.value=form.title.trim()&&form.customerId&&form.value>0&&form.expectedCloseDate&&form.ownerId&&form.probability>=0&&form.probability<=100?'':'請完成所有必填欄位，並確認金額與成交機率有效。';if(!error.value)emit('create',{...form,title:form.title.trim()})}
function trap(event:KeyboardEvent){if(event.key!=='Tab'||!dialog.value)return;const list=dialog.value.querySelectorAll<HTMLElement>('button,input,select');const first=list[0],last=list[list.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}
onMounted(()=>void nextTick(()=>titleInput.value?.focus()))
</script>
<template><div class="opportunity-modal" @mousedown.self="emit('close')"><section ref="dialog" role="dialog" aria-modal="true" aria-labelledby="opportunity-modal-title" @keydown.esc="emit('close')" @keydown.tab="trap"><header><div><h2 id="opportunity-modal-title">新增商機</h2><p>建立新的銷售機會</p></div><button type="button" aria-label="關閉新增商機視窗" @click="emit('close')">×</button></header><form novalidate @submit.prevent="submit"><label>商機名稱<input ref="titleInput" v-model="form.title" /></label><label>客戶<select v-model="form.customerId"><option value="">選擇客戶</option><option v-for="customer in props.customers" :key="customer.id" :value="customer.id">{{ customer.companyName }}</option></select></label><label>預估金額<input v-model.number="form.value" type="number" min="1" /></label><label>Pipeline 階段<select :value="form.stage" @change="setStage"><option v-for="stage in stages" :key="stage" :value="stage">{{ opportunityStageLabels[stage] }}</option></select></label><label>成交機率<input v-model.number="form.probability" type="number" min="0" max="100" :disabled="form.stage==='won'||form.stage==='lost'" /></label><label>預計成交日期<input v-model="form.expectedCloseDate" type="date" /></label><label>負責人<select v-model="form.ownerId"><option value="">選擇負責人</option><option v-for="member in props.members" :key="member.id" :value="member.id">{{ member.name }}</option></select></label><p v-if="error" role="alert">{{ error }}</p><footer><button type="button" @click="emit('close')">取消</button><button type="submit">建立商機</button></footer></form></section></div></template>
<style scoped>.opportunity-modal{align-items:center;background:rgb(15 23 42 / 45%);display:flex;inset:0;justify-content:center;padding:var(--space-4);position:fixed;z-index:40}.opportunity-modal section{background:var(--color-surface);border-radius:var(--radius-lg);box-shadow:var(--shadow-lg);max-height:calc(100vh - 2rem);max-width:36rem;overflow:auto;padding:var(--space-6);width:100%}header{display:flex;justify-content:space-between}h2,p{margin:0}h2{color:var(--color-text);font-size:1.25rem}header p{color:var(--color-text-muted);font-size:.8125rem;margin-top:var(--space-1)}header>button{background:transparent;border:0;border-radius:var(--radius-sm);font-size:1.5rem;height:2.5rem;width:2.5rem}form{display:grid;gap:var(--space-3);margin-top:var(--space-5)}label{color:var(--color-text-secondary);display:grid;font-size:.8125rem;font-weight:700;gap:var(--space-1)}input,select{background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-md);font:inherit;min-height:2.5rem;padding:0 var(--space-2)}input:focus-visible,select:focus-visible,button:focus-visible{outline:3px solid #93c5fd;outline-offset:2px}form p{color:var(--color-danger-strong);font-size:.75rem}footer{display:flex;gap:var(--space-3);justify-content:flex-end}footer button{border:1px solid var(--color-border);border-radius:var(--radius-md);font:inherit;font-weight:700;min-height:2.5rem;padding:0 var(--space-4)}footer button:last-child{background:var(--color-accent);border-color:var(--color-accent);color:white}@media(max-width:31rem){.opportunity-modal{align-items:flex-end;padding:0}.opportunity-modal section{border-radius:var(--radius-lg) var(--radius-lg) 0 0;padding:var(--space-5)}}</style>
