<script setup lang="ts">
import { nextTick, onBeforeUnmount, ref } from 'vue'
import type { OpportunityStage, SalesOpportunity } from '../../types/opportunity'
import { opportunityStageLabels, formatOpportunityCurrency } from '../../utils/opportunity'
import { formatCustomerDate } from '../../utils/customer'
const props = defineProps<{ opportunity: SalesOpportunity; customerName: string; ownerName: string; dragging?: boolean }>()
const emit = defineEmits<{ dragend: []; dragstart: [id: string]; stageChange: [id: string, stage: OpportunityStage] }>()
const open = ref(false); const root = ref<HTMLElement | null>(null); const menu = ref<HTMLElement | null>(null); const button = ref<HTMLButtonElement | null>(null)
const stages: OpportunityStage[] = ['lead', 'contacted', 'proposal', 'negotiation', 'won', 'lost']
function close(focus = false) { open.value = false; if (focus) void nextTick(() => button.value?.focus()) }
function toggle() { open.value = !open.value; if (open.value) void nextTick(() => menu.value?.querySelector<HTMLButtonElement>('button:not(:disabled)')?.focus()) }
function select(stage: OpportunityStage) { emit('stageChange', props.opportunity.id, stage); close(true) }
function moveMenuFocus(event: KeyboardEvent, direction: number) { const items = [...(menu.value?.querySelectorAll<HTMLButtonElement>('button:not(:disabled)') ?? [])]; const index = items.indexOf(document.activeElement as HTMLButtonElement); items[(index + direction + items.length) % items.length]?.focus() }
function outside(event: PointerEvent) { if (open.value && !root.value?.contains(event.target as Node)) close() }
document.addEventListener('pointerdown', outside); onBeforeUnmount(() => document.removeEventListener('pointerdown', outside))
</script>
<template>
  <article class="opportunity-card" :class="{ 'opportunity-card--dragging': dragging }" draggable="true" @dragstart="emit('dragstart', opportunity.id)" @dragend="emit('dragend')">
    <header><div><h3>{{ opportunity.title }}</h3><p>{{ customerName }}</p></div><div ref="root" class="opportunity-card__actions" @keydown.esc.prevent="close(true)"><button ref="button" type="button" aria-haspopup="menu" :aria-expanded="open" :aria-label="`變更 ${opportunity.title} 階段`" @click="toggle">⋯</button><div v-if="open" ref="menu" role="menu" @keydown.down.prevent="moveMenuFocus($event, 1)" @keydown.up.prevent="moveMenuFocus($event, -1)"><button v-for="stage in stages" :key="stage" type="button" role="menuitem" :disabled="stage === opportunity.stage" @click="select(stage)">移至{{ opportunityStageLabels[stage] }}</button></div></div></header>
    <div class="opportunity-card__metrics"><strong>{{ formatOpportunityCurrency(opportunity.value) }}</strong><span>{{ opportunity.probability }}%</span></div>
    <div class="opportunity-card__meta"><span>{{ ownerName }}</span><time :datetime="opportunity.expectedCloseDate">預計 {{ formatCustomerDate(opportunity.expectedCloseDate) }}</time></div>
  </article>
</template>
<style scoped>
.opportunity-card{background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-md);box-shadow:var(--shadow-sm);cursor:grab;display:grid;gap:var(--space-3);padding:var(--space-4);transition:border-color 160ms ease,box-shadow 160ms ease,opacity 160ms ease,transform 160ms ease}.opportunity-card:hover{border-color:var(--color-border-strong);box-shadow:var(--shadow-md);transform:translateY(-1px)}.opportunity-card--dragging{cursor:grabbing;opacity:.55;transform:scale(.985)}header{align-items:flex-start;display:flex;gap:var(--space-2);justify-content:space-between}h3,p{margin:0}h3{color:var(--color-text);font-size:.9375rem;line-height:1.4}header p{color:var(--color-text-muted);font-size:.75rem;margin-top:var(--space-1)}.opportunity-card__actions{position:relative}.opportunity-card__actions>button{background:transparent;border:0;border-radius:var(--radius-sm);color:var(--color-text-secondary);cursor:pointer;font-size:1.35rem;height:2rem;line-height:1;padding:0;width:2rem}.opportunity-card__actions>button:hover,.opportunity-card__actions>button[aria-expanded=true]{background:var(--color-surface-subtle)}.opportunity-card__actions>button:focus-visible,.opportunity-card__actions div button:focus-visible{outline:3px solid #93c5fd;outline-offset:2px}.opportunity-card__actions div{background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-md);box-shadow:var(--shadow-lg);display:grid;min-width:9rem;padding:var(--space-1);position:absolute;right:0;top:calc(100% + var(--space-1));z-index:5}.opportunity-card__actions div button{background:transparent;border:0;border-radius:var(--radius-sm);color:var(--color-text-secondary);font:inherit;font-size:.8125rem;min-height:2.25rem;text-align:left}.opportunity-card__actions div button:hover:not(:disabled){background:var(--color-accent-soft);color:var(--color-accent-strong)}.opportunity-card__actions div button:disabled{color:var(--color-text-muted);font-weight:700}.opportunity-card__metrics{align-items:center;display:flex;justify-content:space-between}.opportunity-card__metrics strong{color:var(--color-text);font-size:1rem;font-variant-numeric:tabular-nums}.opportunity-card__metrics span{background:var(--color-accent-soft);border:1px solid #dfe5ff;border-radius:999px;color:var(--color-accent-strong);font-size:.6875rem;font-weight:750;padding:.25rem var(--space-2)}.opportunity-card__meta{border-top:1px solid var(--color-border);color:var(--color-text-muted);display:flex;font-size:.75rem;gap:var(--space-2);justify-content:space-between;padding-top:var(--space-2)}@media(prefers-reduced-motion:reduce){.opportunity-card{transition:none}}
</style>
